<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;


class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // Fragrance(BEST SELLER)
        Product::create([
            'name' => 'LOST CHERRY',
            'price' => 368,
            'description' => 'LOST CHERRYS CANDY-LIKE GLEAM OF EXOTIC BLACK CHERRY AND LIQUEUR, TOUCHED WITH TEASING ALMOND, GIVES WAY TO A TURKISH ROSE AND JASMINE SAMBAC BLEND THAT PENETRATE THE SENSES. THE FULL-BODIED PERFUME ATTAINS FANTASY-LIKE LEVELS OF INSATIABILITY',
            'image' => 'https://i1.adis.ws/i/tom_ford/T6-LOSTCHERRY_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'LOST CHERRY IS CONTAINED IN A LUSCIOUS, DEEP CHERRY-RED BOTTLE. CAPTURING THE SCENT’S DICHOTOMY OF SWEET AND DARK, THE FLACON IS ADORNED WITH A PALE PINK LABEL, THE COLOR OF CHERRY BLOSSOMS ',
            'categories' => ['women', 'fragrance', 'best_sellers'],
        ]);

        Product::create([
            'name' => 'FLEUR DE PORTOFINO',
            'price' => 263,
            'description' => ' PRIVATE BLEND FLEUR DE PORTOFINO IS INSPIRED BY THE CASCADES OF WHITE FLOWERS THAT SPILL OFF THE BRANCHES OF THE WHITE ACACIA BELOVED SHADE TREE THAT DOTS THE MEDITERRANEAN GARDENS AND LINES ITS TRANQUIL AVENUES. FLEUR DE PORTOFINO CREATES A CRISP AND BRIGHT FLORAL ACCORD FROM THIS BLOOM, THEN SURROUNDS IT WITH EFFERVESCENT CITRUSES AND ACACIA HONEY. THE FRAGRANCE CREATES AN EFFECT OF SHEER FLORAL POSSESSION THAT IS INCOMPARABLY HYPNOTIC AND EXTREMELY BOLD.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T3-FLEUR_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'FLEUR DE PORTOFINO IS CONTAINED IN A LUSCIOUS, LIGHT AQUA-BLUE BOTTLE. CAPTURING THE SCENT’S DICHOTOMY OF WHITE FLOWER AND WHITE ACACIA BELOVED SHADE TREE, THE BOTTLE IS ADORNED WITH A GOLD LABEL',
            'categories' => ['women', 'fragrance', 'best_sellers'],
        ]);

        // Fragrance(DISCOVER_PRIVATE_BLEND)
        Product::create([
            'name' => 'SANTAL BLUSH',
            'price' => 263,
            'description' => ' TOM FORD SANTAL BLUSH IS A MESMERIZING, SPICY WOOD ORIENTAL. A TEXTURED FUSION OF CREAMY SANDALWOOD AND EXOTIC EASTERN SPICES IS ENHANCED WITH INTOXICATING FLORALS AND SUMPTUOUS WOODS TO CREATE SOFT, NAKED GLAMOUR WITH A MYSTERIOUS SPIRIT OF MODERN EARTHINESS. ITS NUDE JUICE AND BLUSH COLORED PACKAGING ARE AS SENSUAL AS A BEAUTIFULLY CONTOURED NUDE FACE',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0-SANTAL_OC_50ML_A?$large$&bg=rgb(255,255,255)',
            'item_detail' => 'SANTAL BLUSH IS IN A WOOD COLOR BOTTLE WITH A PULL OFF SQUARE CAP, THE BODY OF THE BOTTLE IS RECTANGLUAR, WITH A GOLD LABLE ON THE FRONT',
            'categories' => ['women', 'fragrance', 'discover_private_blend'],
        ]);

        Product::create([
            'name' => 'MANDARINO DI AMALFI',
            'price' => 263,
            'description' => 'EFFERVESCENT. TEXTURED. LUMINOUS. PRIVATE BLEND MANDARINO DI AMALFI CAPTURES THE CALM IDYLL OF THE WHITEWASHED VILLAS DOTTING THE CLIFFSIDES OF AMALFI. CITRUS FRUITS WAFT THEIR AROMA WITH A TONIC-LIKE EFFECT, AND EVENING COMES ON WITH A WARM BREEZE OF NIGHT-BLOOMING FLOWERS; THE AIR IS SCENTED WITH MINT, THYME AND WILDFLOWERS',
            'image' => 'https://i1.adis.ws/i/tom_ford/T1-MANDARINO_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'MANDARINO DI AMALFIIS IN A SEA BLUE COLOR BOTTLE WITH A PULL OFF SQUARE CAP, THE BODY OF THE BOTTLE IS RECTANGLUAR, WITH A GOLD LABLE ON THE FRONT',
            'categories' => ['women', 'fragrance', 'discover_private_blend'],
        ]);

        // Fragrance(PRIVATE BLEND)
        Product::create([
            'name' => 'SOLEIL BLANC ALL OVER BODY SPRAY',
            'price' => 79,
            'description' => 'TEMPERATURES RISE IN NEW LUXURIOUS SKIN EXPERIENCES FEATURING PRIVATE BLEND SOLEIL BLANC, INSPIRED BY REMOTE PRIVATE ISLANDS WHERE SUMMER LASTS ALL YEAR AND ONE DAY SEAMLESSLY BLENDS INTO THE NEXT. EXPERIENCE THE INVIGORATING ALL OVER BODY SPRAY INFUSED WITH SULTRY AND SENSUAL SCENT OF SOLEIL BLANC, ADDING A NEW DIMENSION TO THE TOM FORD SOLEIL EXPERIENCE. SPRAY ALL OVER THE BODY, AVOIDING FACE AND EYES',
            'image' => 'https://i1.adis.ws/i/tom_ford/T5AR-01-0001_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'SOLEIL BLANC ALL OVER BODY SPRAY IN A ALL WHITE BOTTLE WITH A PULL OFF LONG CYLINDER CAP, THE BODY OF THE BOTTLE IS ALSO CYLINDER, WITH A GOLD LABLE ON THE FRONT',
            'categories' => ['women', 'fragrance', 'private_blend'],
        ]);

        Product::create([
            'name' => 'CAFE ROSE',
            'price' => 263,
            'description' => 'CAFE ROSE DESCENDS INTO A HIDDEN LABYRINTH, WHERE ROSES FINE BREEDING GIVES WAY TO DARKER PLEASURES',
            'image' => 'https://i1.adis.ws/i/tom_ford/T1-CAFE-ROSE_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'CAFE ROSE IS IN A WOOD COLOR BOTTLE WITH A PULL OFF SQUARE CAP, THE BODY OF THE BOTTLE IS RECTANGLUAR, WITH A GOLD LABLE ON THE FRONT',
            'categories' => ['women', 'fragrance', 'discover_private_blend'],
        ]);

        Product::create([
            'name' => 'NEROLI PORTOFINO FORTE',
            'price' => 368,
            'description' => 'BOLD. SENSUOUS. OPULENT. NEROLI PORTOFINO FORTE IS A BOLD, EXHILARATING INTENSIFICATION OF NEROLI PORTOFINO. THE CLASSIC EAU DE COLOGNE IS RARIFIED WITH RICH, SUBLIME DEPTH AS THE DOUBLE CONCENTRATION OF ITS FLORAL CORE IS LAVISHLY HEIGHTENED TO UTMOST OPULENCE. WITH THE BOLD AND IMPASSIONED INTRODUCTION OF COASTAL ITALIAN WOODS AND SMOOTH LEATHER IN ITS COMPOSITION, NEROLI PORTOFINO FORTE MARKS AN EXQUISITE MONUMENT IN THE NEROLI PORTOFINO COLLECTION',
            'image' => 'https://i1.adis.ws/i/tom_ford/T429_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'NEROLI PORTOFINO IS IN A SEA GREEN COLOR BOTTLE WITH A PULL OFF SQUARE CAP, THE BODY OF THE BOTTLE IS RECTANGLUAR, WITH A GOLD LABLE ON THE FRONT',
            'categories' => ['women', 'fragrance', 'discover_private_blend'],
        ]);


        Product::create([
            'name' => 'ROSE PRICK',
            'price' => 368,
            'description' => ' INSPIRED BY TOM FORDS PRIVATE ROSE GARDEN, ROSE PRICK IS A WILD BOUQUET OF BEAUTIFUL BREEDS OF ROSE - ROSE DE MAI, TURKISH AND BULGARIAN. SHARP AND PRISTINE, THE PIERCING PRICKLES OF THE STEMS HOOK ONTO EACH OTHER, BONDING THEIR BLOOMS IN PINK PERFECTION. A ROSE BY ANY OTHER NAME, WOULDNT BE TOM FORD',
            'image' => 'https://i1.adis.ws/i/tom_ford/T8-ROSE_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'ROSE PRICK IN A LIGHT PINK COLOR BOTTLE WITH A PULL OFF SQUARE CAP, THE BODY OF THE BOTTLE IS RECTANGLUAR, WITH A BLACK LABLE ON THE FRONT',
            'categories' => ['women', 'fragrance', 'private_blend'],
        ]);

        Product::create([
            'name' => 'ROSE GOLD SOLEIL BLANC SHIMMERING BODY OIL',
            'price' => 100,
            'description' => 'TOM FORD SHIMMERING BODY OIL CAPTURES THE SULTRY EFFECT OF SUN-KISSED SUMMER SKIN AND TEMPTS THE SENSES WITH A FRAGRANCE OF SCORCHING SENSUALITY. THIS SILKY AND LIGHTWEIGHT OIL ILLUMINATES THE SKIN WITH SHIMMERS OF GOLD AND PLATINUM LEAF. THE CAPTIVATING FRAGRANCE WRAPS A BOUQUET OF WHITE FLORALS IN A GOLDEN, AMBER-SANDALWOOD EMBRACE AS TEMPTING AS A WHITE-SAND BEACH, AS IRRESISTIBLE AS THE PERFECT TAN',
            'image' => 'https://i1.adis.ws/i/tom_ford/T6M4_ROSEGOLD_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'ROSE GOLD SOLEIL BLANC SHIMMERING BODY OIL IS IN A SEE THROUGH CLEAR BOTTLE WITH A PULL OFF CYLINDER CAP, THE BODY OF THE BOTTLE IS RECTANGLUAR, WITH A GOLD LABLE ON THE FRONT, THE CONTENTS INSIDE OF THE BOTTLE IS ROSE GOLD',
            'categories' => ['women', 'fragrance', 'private_blend'],
        ]);

        //Fragrance(SIGNATURE)
        Product::create([
            'name' => 'BEAU DE JOUR',
            'price' => 136,
            'description' => 'LAVENDER PULSES WITH CLEAN, COMMANDING POWER, AS FLORAL GREEN GERANIUM CREATES A POWERFUL CONTRAST TO THE LEATHER-LIKE OAKMOSS. THE SENSUAL MUSKY WARMTH OF PATCHOULI AND AMBER FURTHER ELEVATE THE MASCULINE INTENSITY.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T8EF_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE BEAU DE JOUR BOTTLE REFLECTS A COOL AND COMMANDING PRESENCE. THE 50ML AND 100ML EDITIONS ARE EACH HOUSED IN A LUXE RIBBED BOTTLE WITH A SLEEK SILVER METAL LABEL AND MATCHING CAP',
            'categories' => ['women', 'fragrance', 'signature'],
        ]);

        Product::create([
            'name' => 'METALLIQUE',
            'price' => 160,
            'description' => 'FORGED WITH ELEGANT BRILLIANCE, TOM FORD METALLIQUE MESMERIZES ITS ADMIRERS WITH A PULSATING FLASH OF MODERN, RESOLUTE FEMININITY, WILLFUL, LUMINOUS AND IN FULL BLOOM. A HIGH-SHINE ARMOR OF ADDICTIVE ALDEHYDES ENVELOP ITS REVERBERATING CORE OF SENSUOUS WHITE FLOWERS, LIKE A METAL VENUS IN FLEURS.
            LIKE AN ARMORED EMBROIDERED DRESS, THE METALLIC SHEATH OF LIGHTER-THAN-AIR ALDEHYDES OPENS THE SCENT LIKE A SECOND SKIN, THE COLLISION OF CRISP VERT DE BERGAMOTE AND PINK PEPPERCORN FURTHER STEELING THE INSATIABILITY OF THE FIRST IMPRESSION.
            BENEATH ITS COOL VENEER, METALLIQUES FLORAL HEART IS AMPLIFIED BY JUXTAPOSING DELICATE WHITE BLOSSOMS OF AUBEPINE AND MUGUET WITH THE NARCOTIC-LIKE NECTAR OF HELIOTROPE.
            AN AURA OF AMBRETTE SEED IMPARTS WARMTH WITH WOODY INFLECTIONS OF PERU BALSAM. THE SOFT SCENT OF VANILLA AND CREAMY SANDALWOOD LAYER AN ADDICTIVE, CONTRASTING FINISH THAT FURTHER DRIVES THE METALLIC SUITING OF THE OPEN',
            'image' => 'https://i1.adis.ws/i/tom_ford/T77-MET_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE METALLIQUE BOTTLE IS ALL WHITE. THE BODY OF THE BOTTLE IS SQAURE. THE CAP OF THE BOTTLE IS CYLINDER IN A GOLD COLOR, THE FRONT OF THE BOTTLE HAS A GOLD LABEL',
            'categories' => ['women', 'fragrance', 'signature'],
        ]);

        Product::create([
            'name' => 'VELVET ORCHID',
            'price' => 136,
            'description' => 'TOM FORD VELVET ORCHID IS AN ORIENTAL FLORAL THAT EVOLVES THE CARNAL GRANDEUR AND SEDUCTIVE POWER OF THE ICONIC TOM FORD BLACK ORCHID INTO AN UBER-FEMININE FRAGRANCE LAVISHED WITH NOTES OF COOL CITRUS, DRAMATIC PETALS, HONEY AND RUM',
            'image' => 'https://i1.adis.ws/i/tom_ford/T1-VELVET_OC_50ML_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE VELVET ORCHID BOTTLE IS PURPLE MATCHING THE CAP. RIBBED BOTTLE WITH A SLEEK GOLD METAL LABEL WITH A GOLD RIBBION UNDER THE CAP',
            'categories' => ['women', 'fragrance', 'signature'],
        ]);

        //FRAGRANCE(CANDLES)
        Product::create([
            'name' => 'PRIVATE BLEND TOBACCO VANILLE CANDLE',
            'price' => 99,
            'description' => 'TOM FORDS AFFECTION FOR LONDON INSPIRED THIS SCENT, REMINISCENT OF AN ENGLISH GENTLEMENS CLUB, REDOLENT WITH SPICE. HE REINVENTS A CLASSIC FRAGRANCE GENRE BY ADDING CREAMY TONKA BEAN, VANILLA, COCOA, DRY FRUIT ACCORDS AND SWEET WOOD SAP FOR A MODERN, OPULENT, AND ALMOST HEADY IMPRESSION THATS ALL MAN, UNLESS WORN BY A WOMAN. 40 HR BURN TIME. PLEASE REMOVE PROTECTIVE COVER BEFORE BURNING',
            'image' => 'https://i1.adis.ws/i/tom_ford/T55M_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE PRIVATE BLEND TOBACCO VANILLE CANDLE IS A COFFEE BROWN COLOR, WITH A SQUARE SHAPE',
            'categories' => ['women', 'men', 'fragrance', 'candles'],
        ]);

        Product::create([
            'name' => 'ROSE PRICK CANDLE',
            'price' => 135,
            'description' => 'INSPIRED BY TOM FORDS PRIVATE ROSE GARDEN, ROSE PRICK IS A WILD BOUQUET OF BEAUTIFUL BREEDS OF ROSE -- ROSE DE MAI, TURKISH AND BULGARIAN. SHARP AND PRISTINE, THE PIERCING PRICKLES OF THE STEMS HOOK ONTO EACH OTHER, BONDING THEIR BLOOMS IN PINK PERFECTION. A ROSE BY ANY OTHER NAME, WOULDNT BE TOM FORD',
            'image' => 'https://i1.adis.ws/i/tom_ford/T9A6_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE ROSE PRICK CANDLE IS A ROSE PINK COLOR, WITH A SQUARE SHAPE',
            'categories' => ['women', 'men', 'fragrance', 'candles'],
        ]);

        Product::create([
            'name' => 'PRIVATE BLEND LOST CHERRY CANDLE',
            'price' => 135,
            'description' => 'LUSCIOUS, TEMPTING, AND INSATIABLE—INNOCENCE INTERSECTS INDULGENCE IN THIS FRAGRANCE. THE OPENING THAT CAPTURES THE CLASSIC PERFECTION OF THE EXOTIC CHERRY FRUIT. BLACK CHERRY’S RIPE FLESH DRIPPING IN CHERRY LIQUEUR GLISTENS WITH A TEASING TOUCH OF BITTER ALMOND. THE HEART BURSTS FORTH IN CHERRY WAVES OF SWEET AND TART. GRIOTTE SYRUP EXPRESSES THE TEXTURED MACERATION OF VOLUPTUOUS FRUITS WHILE BREATHTAKING FLORALS—TURKISH ROSE AND JASMINE SAMBAC—PENETRATE THE SENSES AND SOUL. PERU BALSAM AND ROASTED TONKA AT THE DRYDOWN SUGGEST A NEW PORTRAIT OF AN ICONIC SYMBOL. WHEN BLENDED WITH AN UNEXPECTED MÉLANGE OF SANDALWOOD, VETIVER, AND CEDAR, THE FINISH REACHES FANTASY-INSPIRING LEVELS OF INSATIABILITY',
            'image' => 'https://i1.adis.ws/i/tom_ford/T8MN-01-0001_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE PRIVATE BLEND LOST CHERRY CANDLE IS A DARK RED COLOR, WITH A SQUARE SHAPE',
            'categories' => ['women', 'men', 'fragrance', 'candles'],
        ]);

        //FACE(BRONZER)
        Product::create([
            'name' => 'SKIN ILLUMINATOR',
            'price' => 53,
            'description' => 'INSPIRED BY THE LOOK OF SKIN BATHED IN SUMMER EVENING LIGHT, THIS ILLUMINATOR CREATES AN IRRESISTIBLE, TRANSLUCENT GLOW. ITS PEACH PINK SHADE FLATTERS EVERY SKIN TONE AND ITS HIGHLY MICRONIZED PEARLS DIFFUSE LIGHT FOR A NATURALLY ENHANCED, SUN-KISSED LOOK. APPLY THE ILLUMINATOR ALL OVER THE FACE ON ITS OWN, OR MIXED WITH TOM FORD TRACELESS FOUNDATION, TO ACHIEVE RADIANT AND BALANCED SKIN. THE ILLUMINATOR CAN ALSO BE USED AS A HIGHLIGHTER UNDER OR OVER MAKEUP.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T57F_FIRELUST_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE SKIN ILLUMINATOR IS IN A CYLINDER SEE-THROUGH CLEAR BOTTLE, THE CAP OF THE BOTTLE IS ALL WHITE, THE LABEL IS CIRCLING AROUND THE CAP AND THE BOTTLE IN GOLD',
            'categories' => ['women', 'face', 'bronzer'],
        ]);

        Product::create([
            'name' => 'SHADE AND ILLUMINATE',
            'price' => 89,
            'description' => 'THIS DUET OF HIGHLIGHTING AND SHADING CREAMS IS DESIGNED TO MAKE SCULPTING AND CONTOURING THE FACE REMARKABLY SIMPLE. THE SUPER SHEER, LIGHT SHADE CAN BE USED TO DRAW LIGHT ONTO THE SKIN TO BRIGHTEN AND LIFT THE FACE. THE DARK SHADE DEFINES AND CONTOURS BONES WHILE STAYING INVISIBLE TO THE NAKED EYE',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0PL_INTENSITYONE_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE SHADE AND ILLUMINATE IS IN A RECTANGLUR PALATE, WITH A GOLD LABEL ON THE BOTTOM FRONT. THE PALATTE FLIPS OPEN, THERE ARE TWO SECTIONS, ON TOP THE COLOR IS THE LIGHT SHADE AND ON THE BOTTOM IS THE DARK SHADE ',
            'categories' => ['women', 'face', 'bronzer'],
        ]);

        //FACE(BRUSHES)

        Product::create([
            'name' => 'SMOKEY EYE BRUSH 14',
            'price' => 53,
            'description' => 'A SMOKY EYE BRUSH DESIGNED FOR EXPERT APPLICATION TO ACHIEVE THE ULTIMATE SMOKY EYE',
            'image' => 'https://i1.adis.ws/i/tom_ford/T6CE_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE SMOKEY EYE BRUSH 14 IS A BROWN PEN LIKE BRUSH, THE TOP IS GOLD AND THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'face', 'brushes'],
        ]);

        Product::create([
            'name' => 'BRUSH CLEANSER',
            'price' => 35,
            'description' => 'CLEANSE, DISINFECT AND CONDITION BRUSH FIBERS FOR OPTIMUM PRESERVATION. BRUSH CLEANSER EXTENDS THE LIFE OF TOM FORD BRUSHES WHILE SHORTENING DRYING TIME AFTER CLEANSING.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T6E9_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE BRUSH CLEANSER IS A PINK BOTTLE WITH A GOLD TIP FOR THE SPRAY',
            'categories' => ['women', 'face', 'brushes'],
        ]);

        // CHEEK COLOR
        Product::create([
            'name' => 'SOLEIL SHEER CHEEK DUO',
            'price' => 84,
            'description' => 'TOM FORDS LUXURIOUS EXPERTLY-DESIGNED FACE PALETTE RETURNS IN NUDE GLOW, THREE NEW SENSUAL SUMMER SHADES IN ONE IVORY-AND GOLD-COLORED TOM FORD SOLEIL COMPACT. THREE SHADES OF BLUSH AND HIGHLIGHTER ADD NATURAL DIMENSION AND SENSUOUS COLOR IN A CREAM-LIKE POWDER FORMULA THAT EFFORTLESSLY GLIDES ONTO SKIN WITH A SOFT, EVEN FINISH. MAUVE NUDE BLUSH GIVES CHEEKS THE PERFECT TOUCH OF COLOR, THE PEACH NUDE HIGHLIGHTER MIMICS THE SUN REFLECTING OFF THE SKIN AND THE SULTRY DARK NUDE ENHANCES A HEALTHY RADIANCE. USE SHADES ALONE OR TOGETHER TO CONTOUR A SEDUCTIVE, NATURAL GLOW. PROVIDES SHEER TO MEDIUM COVERAGE, BOTH MATTE AND RADIANT. EMBOSSED WITH TOM FORD LOGO',
            'image' => 'https://i1.adis.ws/i/tom_ford/T44F_LISSOME_OS_F?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'SOLEIL SHEER CHEEK DUO COMES IN A IVORY-AND GOLD-COLORED TOM FORD SOLEIL COMPACT. THE PALETTE FIPS OPEN AND ON TOP IS A LIGHT PINK COLOR WHILE THE BOTTOM IS A DARK PINK COLOR,  ',
            'categories' => ['women', 'face', 'cheek color'],
        ]);

        Product::create([
            'name' => 'CHEEK COLOR',
            'price' => 67,
            'description' => 'COLOR RICH. VELVETY. BUILDABLE. POWDER BLUSH WITH A COLOR-RICH FORMULA THAT GLIDES ONTO SKIN WITH THE COMFORT OF A CREAM. A SUMPTUOUS POWDER BLUSH FORMULATED WITH SPHERICAL PEARLS AND RICH EMOLLIENTS THAT GLIDES ONTO SKIN WITH THE COMFORT OF A CREAM, AND ACHIEVES OUTSTANDING LUMINOSITY AND A VELVETY TRANSPARENCY. SIX BUILDABLE SHADES ALLOW FOR VERSATILE LAYERING OF COLOR, FROM A SEXY GLOW TO A MORE DRAMATIC, COLOR-RICH LOOK',
            'image' => 'https://i1.adis.ws/i/tom_ford/T4LK_FRANTICPINK_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'CHEEK COLOR COMES IN A COFFE BROWN COLOR WIHE A GOLD LABEL ON THE FRONT BOTTOM OF THE PALETTE, THE PALETTE FLIPS OPEN REVELING ITS PINK COLOR ',
            'categories' => ['women', 'face', 'cheek color'],
        ]);

        //FACE(CONCEALER)
        Product::create([
            'name' => 'CONCEALING PEN',
            'price' => 55,
            'description' => 'DESIGNED WITH AN UNIQUE APPLICATOR, THE TOM FORD CONCEALING PEN DELIVERS AN UNDETECTABLE FINISH AS IT CAMOUFLAGES UNDER-EYE CIRCLES AND AREAS OF UNEVEN SKIN TONE AND REDNESS. ITS LUXURIOUS FORMULA, WHICH INCLUDES THE TOM FORD INFUSING COMPLEX TO REJUVENATE SKIN FROM WITHIN, CREATES THE APPEARANCE OF A SMOOTH AND FLAWLESS COMPLEXION. USE ALONE OR WITH TOM FORD FOUNDATIONS.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T1T1_BUFF_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE CONCEALING PEN IS ALL BROWN CYLINDER SHAPED WITH A PULL OFF CAP WITH THE LOGO ON THE CAP,  THE TIP IS CREAM LIKE COLOR AND SOFT',
            'categories' => ['women', 'face', 'concealer'],
        ]);

        Product::create([
            'name' => 'SHADE & ILLUMINATE CONCEALER',
            'price' => 90,
            'description' => 'SHADE AND ILLUMINATE CONCEALER IS A MEDIUM-BUILDABLE, WATERPROOF FORMULA MERGING THREE-DIMENSIONAL SKINCARE WITH THREE-DIMENSIONAL RADIANCE. INFUSED WITH HYALURONIC ACID, THIS CREASE-PROOF CONCEALER MOISTURIZES, SMOOTHS, AND OBSCURES REDNESS, DARK UNDEREYE CIRCLES AND FINE LINES – CREATING A FLAWLESS BASE FOR SHADE AND ILLUMINATE SOFT RADIANCE FOUNDATION.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T926_0N0_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE SHADE & ILLUMINATE CONCEALER IS A CLEAR, SEE THROUGH BOTTLE WITH A GOLD DESIGN AROUND IT, THE CAP IS A PULL OFF ALSO THE COLOR OF BROWN',
            'categories' => ['women', 'face', 'concealer'],
        ]);

        //FACE(FOUNDATION)
        Product::create([
            'name' => 'GLOW TINTED MOISTURIZER',
            'price' => 70,
            'description' => 'HYDRATING. RADIANT. COMPLEXION-PERFECTING. CREATING A FLAWLESS COMPLEXION IS ESSENTIAL TO DESIGNING THE TOM FORD FACE. SEAMLESSLY BLEND THE LUXURIOUS FORMULA INTO SKIN FOR A RADIANT GLOW THAT IMMEDIATELY MOISTURIZES WITH A SHEER HINT OF COMPLEXION-PERFECTING COLOR. INFUSED WITH HYALURONIC ACID AND JOJOBA OILS FOR NOURISHING HYDRATION, THE VEGAN TINTED MOISTURIZER IS PARABEN-FREE, SULFATE-FREE AND SULFITE-FREE. WEIGHTLESS WITH A SMOOTH FINISH, THE FORMULA EVENS SKIN TONE AND SIGNS OF AGING SUCH AS SPOTS, LINES AND WRINKLES. RETEXTURIZED AND FIRM, A FRESH, FLAWLESS CANVAS IS CREATED. SPF 15/PA+++ HELPS TO PROTECT FROM THE HARMFUL EFFECTS OF THE SUN, WHILE NOURISHING ANTIOXIDANTS REPLENISH SKIN FROM THE DAMAGE OF ENVIRONMENTAL STRESSORS',
            'image' => 'https://i1.adis.ws/i/tom_ford/T8C1_BONE_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE GLOW TINTED MOISTURIZER IS IN A SOFT LOTION BOTTON, ALL WHITE, GOLD CAP',
            'categories' => ['women', 'face', 'foundation'],
        ]);

        Product::create([
            'name' => 'TRACELESS FOUNDATION STICK',
            'price' => 89,
            'description' => 'THIS UNIQUE CREAM FOUNDATION FORMULA FEATURES THE NOURISHING TOM FORD INFUSING COMPLEX AND CREATES A FLAWLESS, SMOOTH FINISH. PORTABLE STICK ACHIEVES VERSATILITY IN APPLICATION FOR SHEER MEDIUM OR FULL COVERAGE, ALWAYS BEAUTIFULLY NATURAL AND UNDETECTABLE. WHEN USED AS A CONCEALER, IT SWIFTLY DIMINISHES IMPERFECTIONS, LEAVING A SOFT MATTE FINISH.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0TJ_55BISQUE_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE TRACKLESS FOUNDATION STICK IS A BROWN CYLINDER BOTTLE, WIHT A TWIST OFF CAP, REVELING A BROWN CIRCULAR FOUNDATION',
            'categories' => ['women', 'face', 'foundation'],
        ]);

        Product::create([
            'name' => 'ILLUMINATING PRIMER',
            'price' => 76,
            'description' => 'THE FIRST STEP TO FLAWLESS MAKEUP APPLICATION. THIS REVOLUTIONARY HYBRID PRODUCT SEAMLESSLY BLENDS THE WORLDS OF SKINCARE AND MAKEUP BY COMBINING THE TOM FORD INFUSING COMPLEX WITH SKIN RETEXTURING INGREDIENTS. IT HYDRATES TO INCREASE VITALITY WHILE ENHANCING TEXTURE, AND VISIBLY BRIGHTENING THE SKIN. A LUMINOUS AND FLAWLESS CANVAS IS CREATED FOR COMFORTABLE AND SMOOTH COLOR. APPLY A SMALL AMOUNT TO FACE AFTER CONCENTRATE AND MOISTURIZER AND BEFORE FOUNDATION. DERMATOLOGIST TESTED',
            'image' => 'https://i1.adis.ws/i/tom_ford/T8H1_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE ILLUMINATING PRIMER IS A CLEAR SEE THROUGH BOTTLE WITH A BROWN CAP AND A GOLD LABEL OF THE BRAND',
            'categories' => ['women', 'face', 'powder'],
        ]);

        //FACE(POWEDER)
        Product::create([
            'name' => 'ILLUMINATING POWDER',
            'price' => 84,
            'description' => 'LIGHT-DIFFUSING. SILK-LIKE. WEIGHTLESS. A WEIGHTLESS AND UNDETECTABLE MICRO-FINE POWDER THAT ENSURES A NATURAL AND EVEN FINISH. A WEIGHTLESS AND UNDETECTABLE MICRO-FINE POWDER WITH SPECIALLY COATED PIGMENTS CREATES A DIAPHANOUS VEIL OF LIGHT ON THE FACE. ULTRA-GLIDING TEXTURE BLENDS FLUIDLY ON SKIN, MOISTURIZING AND REDEFINING THE COMPLEXION TO ENSURE A NATURAL AND EVEN FINISH. CUSTOM APPLICATOR BRUSH INCLUDED',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0T8_TRANSLUCENT_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE ILLUMINATING POWDER IS IN A BROWN PALETTE WITH A GOLD LABLE ON THE FRONT BOTTOM. THE PALETTE FLIPS OPEN REVELING THE WHITE POWEDER AND A BRUSH',
            'categories' => ['women', 'face', 'powder'],
        ]);

        //FACE(SKINCARE)
        Product::create([
            'name' => 'TOM FORD RESEARCH CREME CONCENTRATE',
            'price' => 450,
            'description' => 'A HYDRATING, ULTRA-RICH CREAM THAT FEELS FEATHER-LIGHT ON SKIN. IT COCOONS DEHYDRATED SKIN WITH AN IMMEDIATE SENSE OF COMFORT. THE CREAM MELTS INTO SKIN, INFUSING IT WITH LUMINOSITY AND RADIANCE FOR AN ENERGIZED APPEARANCE. SKIN IS RECHARGED AND VISIBLY RENEWED, WHILE THE APPEARANCE OF LINES AND WRINKLES IS DIMINISHED',
            'image' => 'https://i1.adis.ws/i/tom_ford/T6CK_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE TOM FORD RESEARCH CREME CONCENTRATE IS IN A ALL WHILE CONTAINER WITH A TWIST OFF CAP',
            'categories' => ['women', 'face', 'skincare'],
        ]);

        Product::create([
            'name' => 'TOM FORD RESEARCH SERUM CONCENTRATE',
            'price' => 350,
            'description' => 'A LUXURIOUS, HIGHLY POTENT SERUM THAT ABSORBS INSTANTLY INTO SKIN TO VISIBLY ENHANCE TEXTURE, TONE, AND LUMINOSITY. THE SERUM CONCENTRATE IMMEDIATELY JUMPSTARTS TIRED LOOKING SKIN, HELPING IT TO ABSORB AND RETAIN MOISTURE. THE APPEARANCE OF PORES, LINES, AND WRINKLES IS DIMINISHED WHILE SKINS HEALTHY RADIANCE AND VISIBLE RESILIENCY ARE RENEWED',
            'image' => 'https://i1.adis.ws/i/tom_ford/T5AH_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE TOM FORD RESEARCH SERUM CONCENTRATE IS IN A WHITE CYLINDER BOTTLE WITH A BROWN RIBBION BELOW THE CAP',
            'categories' => ['women', 'face', 'skincare'],
        ]);

        //LIPS(LIP COLOR)
        Product::create([
            'name' => '71 CONTEMPT',
            'price' => 58,
            'description' => 'FROM SECOND-SKIN NUDES TO BLAZING REDS, EACH LIP COLOR DELIVERS A MOISTURIZING, FADE-RESISTANT, COLOR-TRUE FINISH FOR EIGHT HOURS OF INTENSE, SATURATED SHADE FIDELITY AND IMPECCABLE POLISH OFFERED IN ICONIC TOM FORD PACKAGING',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0T3_CONTEMPT_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE 71 CONTEMPT A BROWN RECTANGLUAR LIPSTICK WITH A GOLD CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip color'],
        ]);

        Product::create([
            'name' => '15 WILD GINGER',
            'price' => 58,
            'description' => 'FROM SECOND-SKIN NUDES TO BLAZING REDS, EACH LIP COLOR DELIVERS A MOISTURIZING, FADE-RESISTANT, COLOR-TRUE FINISH FOR EIGHT HOURS OF INTENSE, SATURATED SHADE FIDELITY AND IMPECCABLE POLISH OFFERED IN ICONIC TOM FORD PACKAGING',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0T3_WILDGINGER_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE 15 WILD GINGER A BROWN RECTANGLUAR LIPSTICK WITH A GOLD CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_color'],
        ]);

        Product::create([
            'name' => '84 EXOTICA',
            'price' => 58,
            'description' => 'FROM SECOND-SKIN NUDES TO BLAZING REDS, EACH LIP COLOR DELIVERS A MOISTURIZING, FADE-RESISTANT, COLOR-TRUE FINISH FOR EIGHT HOURS OF INTENSE, SATURATED SHADE FIDELITY AND IMPECCABLE POLISH OFFERED IN ICONIC TOM FORD PACKAGING',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0T3_EXOTICA_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE 84 EXOTICA A BROWN RECTANGLUAR LIPSTICK WITH A GOLD CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_color'],
        ]);

        //LIPS(BOYS & GIRLS)

        Product::create([
            'name' => '35 BELLA',
            'price' => 36,
            'description' => '50 BOYS MEET 50 GIRLS. TOM FORDS CELEBRATED CLUTCH-SIZED LIPS AND BOYS COLLECTION. NAMED AFTER MEN AND WOMEN HE ADMIRES, FROM INTIMATES TO COLLABORATORS FROM AROUND THE WORLD. DESIGNED TO BE WORN ON THEIR OWN OR LAYERED WITH ONE ANOTHER, EACH TRANSFORMING COLOR AND FINISH AMPLIFIES A WOMAN OR MANS INDIVIDUALITY WHILE INCITING AN INSATIABLE DESIRE TO TRY MORE THAN ONE. THE DECADENT WARDROBE OF RICH, SPECIALLY TREATED PIGMENTS ARE BLENDED TO DELIVER PURE COLOR IN ULTRA-KISSABLE MATTE, CREAM AND METALLIC FINISHES',
            'image' => 'https://i1.adis.ws/i/tom_ford/T31H-1_BELLA_OS_A?sm=aspect&aspect=3.14:4&w=747&img404=img404&bg=rgb(218,218,218)',
            'item_detail' => 'THE 35 BELLA A WHITE RECTANGLUAR LIPSTICK WITH A GOLD OUTLINE AND A GOLD CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'boys_girls'],
        ]);

        Product::create([
            'name' => '07 STERLING',
            'price' => 36,
            'description' => '50 BOYS MEET 50 GIRLS. TOM FORDS CELEBRATED CLUTCH-SIZED LIPS AND BOYS COLLECTION. NAMED AFTER MEN AND WOMEN HE ADMIRES, FROM INTIMATES TO COLLABORATORS FROM AROUND THE WORLD. DESIGNED TO BE WORN ON THEIR OWN OR LAYERED WITH ONE ANOTHER, EACH TRANSFORMING COLOR AND FINISH AMPLIFIES A WOMAN OR MANS INDIVIDUALITY WHILE INCITING AN INSATIABLE DESIRE TO TRY MORE THAN ONE. THE DECADENT WARDROBE OF RICH, SPECIALLY TREATED PIGMENTS ARE BLENDED TO DELIVER PURE COLOR IN ULTRA-KISSABLE MATTE, CREAM AND METALLIC FINISHES',
            'image' => 'https://i1.adis.ws/i/tom_ford/T31H-1_07STERLING_OS_A?sm=aspect&aspect=3.14:4&w=648&img404=img404&bg=rgb(218,218,218)',
            'item_detail' => 'THE 07 STERLING A BROWN RECTANGLUAR LIPSTICK WITH A GOLD CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'boys_girls'],
        ]);

        //LIPS(LIP LACQUER)
        Product::create([
            'name' => 'PUSSYCAT',
            'price' => 58,
            'description' => 'TOM FORD ELEVATES LIQUID LIPSTICK IN A MOISTURE RICH, SOFT-MATTE FORMULA. INTENSE, SATURATED COLOR COATS LIPS WITH SUPPLE COMFORT. PIGMENT-MAXIMIZING TECHNOLOGY ENVELOPS CONCENTRATED PIGMENTS IN ULTRA-CUSHION-LIKE EMOLLIENTS, CREATING A SMOOTH, SECOND-SKIN FILM ON LIPS. 10 LIQUID MATTES PAINT ON MINERAL POWDER-INFUSED COLOR, FROM THE PLAYFUL BERRY OF HABITUAL TO THE COMMANDING REDS OF JAGUAR AND OVERPOWER',
            'image' => 'https://i1.adis.ws/i/tom_ford/T725_PUSSYCAT_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE PUSSYCAT A BROWN RECTANGLUAR LIPSTICK WITH A BROWN CAP AND A GOLD LABEL BELOW THE CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_lacquer'],
        ]);

        Product::create([
            'name' => '69 NIGHT MAUVE',
            'price' => 58,
            'description' => 'TOM FORD ELEVATES LIQUID LIPSTICK IN A MOISTURE RICH, SOFT-MATTE FORMULA. INTENSE, SATURATED COLOR COATS LIPS WITH SUPPLE COMFORT. PIGMENT-MAXIMIZING TECHNOLOGY ENVELOPS CONCENTRATED PIGMENTS IN ULTRA-CUSHION-LIKE EMOLLIENTS, CREATING A SMOOTH, SECOND-SKIN FILM ON LIPS. 10 LIQUID MATTES PAINT ON MINERAL POWDER-INFUSED COLOR, FROM THE PLAYFUL BERRY OF HABITUAL TO THE COMMANDING REDS OF JAGUAR AND OVERPOWER',
            'image' => 'https://i1.adis.ws/i/tom_ford/T725_69NIGHTMAUVE_OS_A?$pdp_hero_mob$&bg=rgb(255,255,255)',
            'item_detail' => 'THE PUSSYCAT A BROWN RECTANGLUAR LIPSTICK WITH A BROWN CAP AND A GOLD LABEL BELOW THE CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_lacquer'],
        ]);

        Product::create([
            'name' => 'OVERPOWER',
            'price' => 58,
            'description' => 'TOM FORD ELEVATES LIQUID LIPSTICK IN A MOISTURE RICH, SOFT-MATTE FORMULA. INTENSE, SATURATED COLOR COATS LIPS WITH SUPPLE COMFORT. PIGMENT-MAXIMIZING TECHNOLOGY ENVELOPS CONCENTRATED PIGMENTS IN ULTRA-CUSHION-LIKE EMOLLIENTS, CREATING A SMOOTH, SECOND-SKIN FILM ON LIPS. 10 LIQUID MATTES PAINT ON MINERAL POWDER-INFUSED COLOR, FROM THE PLAYFUL BERRY OF HABITUAL TO THE COMMANDING REDS OF JAGUAR AND OVERPOWER',
            'image' => 'https://i1.adis.ws/i/tom_ford/T725_OVERPOWER_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE OVERPOWER A BROWN RECTANGLUAR LIPSTICK WITH A BROWN CAP AND A GOLD LABEL BELOW THE CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_lacquer'],
        ]);

        //LIPS(LIP GLOSS)
        Product::create([
            'name' => 'IN THE BUFF',
            'price' => 56,
            'description' => 'THE NEXT EVOLUTION OF LIP GLOSS GOES LIGHT-AS-AIR IN SHEER-TO MEDIUM COVERAGE. INFUSED WITH THREE OILS - AVOCADO, OLIVE AND JOJOBA - AND HOLLOW POWDERS FOR AIRY COMFORT, THE LIQUID BALM GLACE HYDRATES LIPS WITH FULL-LOOKING, ZERO-GRAVITY WEAR AND GLEAM.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T76A_INTHEBUFF_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'IN THE BUFF A CLEAR RECTANGLUAR LIP GLOSS WITH A BROWN CAP AND A GOLD LABEL BELOW THE CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_gloss'],
        ]);

        Product::create([
            'name' => '09 AURA',
            'price' => 58,
            'description' => 'THE NEXT EVOLUTION OF LIP GLOSS GOES LIGHT-AS-AIR IN SHEER-TO MEDIUM COVERAGE. INFUSED WITH THREE OILS - AVOCADO, OLIVE AND JOJOBA - AND HOLLOW POWDERS FOR AIRY COMFORT, THE LIQUID BALM GLACE HYDRATES LIPS WITH FULL-LOOKING, ZERO-GRAVITY WEAR AND GLEAM.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T76A_09AURA_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => '09 AURA A CLEAR RECTANGLUAR LIP GLOSS WITH A BROWN CAP AND A GOLD LABEL BELOW THE CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_gloss'],
        ]);

        Product::create([
            'name' => '20 PHANTOME',
            'price' => 58,
            'description' => 'THE NEXT EVOLUTION OF LIP GLOSS GOES LIGHT-AS-AIR IN SHEER-TO MEDIUM COVERAGE. INFUSED WITH THREE OILS - AVOCADO, OLIVE AND JOJOBA - AND HOLLOW POWDERS FOR AIRY COMFORT, THE LIQUID BALM GLACE HYDRATES LIPS WITH FULL-LOOKING, ZERO-GRAVITY WEAR AND GLEAM.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T76A_20PHANTOME_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => '20 PHANTOME A CLEAR RECTANGLUAR LIP GLOSS WITH A BROWN CAP AND A GOLD LABEL BELOW THE CAP, THE TIP IS OVAL SHAPED',
            'categories' => ['women', 'lips', 'lip_gloss'],
        ]);

        //MEN(BEARD)
        Product::create([
            'name' => 'BEARD COMB',
            'price' => 40,
            'description' => 'THIS HIGH-QUALITY BEARD COMB IS DESIGNED TO GLIDE COMFORTABLY THROUGH THE BEARD, MINIMIZING DAMAGE TO THE FACIAL HAIR OR IRRITATION TO THE SKIN. CRAFTED FOR DURABILITY AND SIZED FOR PORTABILITY, IT SMOOTHES UNRULY FACIAL HAIR AND HELPS DISTRIBUTE BEARD OIL EVENLY, LEAVING THE BEARD LOOKING WELL-KEPT AND LUSTROUS',
            'image' => 'https://i1.adis.ws/i/tom_ford/T3H9-01-0001_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE BEARD COMB IS HAND HELD WITH ITS BROWN AND ORANGE MIX COLOR',
            'categories' => ['men', 'beard'],
        ]);

        Product::create([
            'name' => 'SHAVE OIL',
            'price' => 67,
            'description' => 'THIS ULTRA-LUXE SHAVE OIL MOISTURIZES, CONDITIONS AND CUSHIONS FOR A CLOSE SHAVE. SOOTHING AND CALMING, SHAVE OIL HELPS PROTECT SKIN DURING SHAVING AND HELPS SOOTHE THE LOOK OF IRRITATION WHILE CREATING AN INVIGORATING OLFACTIVE EXPERIENCE FEATURING A UNIQUE SCENT BLEND. THE LIGHTWEIGHT FORMULA CAN BE USED ALONE OR UNDER SHAVE CREAM. FEATURES: TOM FORD FOR MEN SKIN CALMING COMPLEX TOM FORD PURIFYING COMPLEX USAGE WET FACE WITH WARM WATER THEN MASSAGE A FEW DROPS INTO BEARD. SHAVE AS USUAL. CAN BE USED UNDER SHAVE CREAM FOR A MORE SENSORIAL SHAVE',
            'image' => 'https://i1.adis.ws/i/tom_ford/T445-01-0001_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE SHAVE OIL COMES IN A COFFEE BROWN COLOR BOTTLE WITH A PULL OFF BROWN COLOR CAP',
            'categories' => ['men', 'beard'],
        ]);

        //MEN(BODY)
        Product::create([
            'name' => 'BEAU DE JOUR ALL OVER BODY SPRAY',
            'price' => 49,
            'description' => 'BEAU DE JOUR PRESENTS THE PERFECTLY GROOMED GENTLEMAN WHO CONSIDERS EVERY DETAIL. HE EXHIBITS THE BEST VERSION OF HIMSELF TO THE WORLD, BUT BENEATH THE SURFACE IS SOMETHING DEEPER, REFRESHING AND SUBLIME IN ALL ITS LAYERS. A FRESH, COMMANDING ENTRANCE OF LAVENDER FROM PROVENCE INTRODUCES THE CLEAN AND FERVENT FACETS OF THE BEAU DE JOUR SCENT. THE COOL AND REFRESHING OPEN IS FURTHER AMPLIFIED WITH AN INFUSION OF AN ENERGETIC HYBRID OF LAVENDERS. THE CORE BEATS WITH THE HERBAL INFLECTION OF AFRICAN ROSEMARY AND FLORAL GREEN GERANIUM WITH ITS SUBTLE MINT INFLECTION, A POWERFUL CONTRAST TO THE LEATHER-LIKE WARMTH OF OAKMOSS AND THE ELECTRIC GREEN OF BASIL. PATCHOULI AND AMBER CREATE AN EARTHY FOUNDATION OF RADIANT WOOD AND SENSUAL MUSKY WARMTH, FURTHER ELEVATING BEAU DE JOUR’S REFRESHING NOTION OF MASCULINITY THROUGH THE FINISH',
            'image' => 'https://i1.adis.ws/i/tom_ford/T8EF-AOB_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE BEAU DE JOUR BODY SPRAY IS A ALL WHITE BOTTLE WITH A GRAY LABEL AT THE BOTTOM, AND A PULL OFF WHITE CAP',
            'categories' => ['men', 'body'],
        ]);

        Product::create([
            'name' => 'NEROLI PORTOFINO ALL OVER BODY SPRAY',
            'price' => 79,
            'description' => 'TO TOM FORD, THIS SCENT PERFECTLY CAPTURES THE COOL BREEZES, SPARKLING CLEAR WATER AND LUSH FOLIAGE OF THE ITALIAN RIVIERA. HIS REINVENTION OF A CLASSIC EAU DE COLOGNE FEATURES CRISP CITRUS OILS, SURPRISING FLORAL NOTES AND AMBER UNDERTONES TO LEAVE A SPLASHY YET SUBSTANTIVE IMPRESSION. EXPERIENCE THE NEW INVIGORATING ALL OVER BODY SPRAY LIGHTLY SCENTED WITH NEROLI PORTOFINO, ADDING A NEW DIMENSION TO THE NEROLI PORTOFINO BATH & BODY COLLECTION.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T1LG-01-0001_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE NEROLI PORTOFINO BODY SPRAY IS A SEA GREEN BOTTLE WITH A GOLD LABEL AT FRONT, AND A PULL OFF SEA GREEN CAP',
            'categories' => ['men', 'body'],
        ]);

        Product::create([
            'name' => 'ROSE PRICK ALL OVER BODY SPRAY',
            'price' => 100,
            'description' => 'INSPIRED BY TOM FORDS PRIVATE ROSE GARDEN, ROSE PRICK IS A WILD BOUQUET OF BEAUTIFUL BREEDS OF ROSE-ROSE DE MAI, TURKISH AND BULGARIAN. SHARP AND PRISTINE, THE PIERCING PRICKLES OF THE STEMS HOOK ONTO EACH OTHER, BONDING THEIR BLOOMS IN PINK PERFECTION. A ROSE BY ANY OTHER NAME, WOULDNT BE TOM FORD.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T9A5_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE ROSE PRICK BODY SPRAY IS A PINK BOTTLE WITH A BLACK LABEL AT FRONT, AND A PULL OFF PINK CAP',
            'categories' => ['men', 'body'],
        ]);

        //MEN(FACE)
        Product::create([
            'name' => 'EXFOLIATING ENERGY SCRUB',
            'price' => 57,
            'description' => 'TOM FORD EXFOLIATING ENERGY SCRUB SPECIALLY-FORMULATED FOR NORMAL TO OILY SKIN, THIS ENERGIZING SCRUB CONTAINS CRUSHED APRICOT SEEDS TO HELP REMOVE DEAD SKIN CELLS AND UNCLOG PORES FOR CLEAN AND POLISHED-LOOKING SKIN. FEATURES: TOM FORD FOR MEN SKIN CALMING COMPLEX TOM FORD PURIFYING COMPLEX USAGE APPLY TO WET FACE AND NECK WITH FINGERTIPS IN A CIRCULAR MOTION. RINSE.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T432-01-0001_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE EXFOLIATING ENERGY SCRUB IS A CLEAR SEE THROUGH BOTTLE, WITH A BROWN CAP, THE CONTENTS INSIDE THE BOTTLE ARE IS A ORANGE COLOR',
            'categories' => ['men', 'face'],
        ]);

        Product::create([
            'name' => 'INTENSIVE PURIFYING MUD MASK',
            'price' => 67,
            'description' => 'A WEEKLY CLAY MASK TREATMENT IS INTEGRAL TO MY PERSONAL GROOMING ROUTINE. I DEVELOPED THIS TIME-SIGNALING DETOXIFYING MUD MASK TO HELP FIGHT THE DULLING AND IRRITATING EFFECTS OF BUSY LIFESTYLE ON THE SKIN. AS THE MASK TURNS LIGHT GRAY, IT DRAWS OUT OIL, DIRT AND TOXINS. WHEN YOU RINSE IT OFF, YOUR SKIN FEELS CLEAN, SMOOTH, CONDITIONED, AND YOU LOOK REVITALIZED.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T23C-01-0001_OC_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE INTENSIVE PURIFYING MUD MASK IS A BROWN BOTTLE, WITH A BROWN CAP',
            'categories' => ['men', 'face'],
        ]);

        //EYES(BROWS)
        Product::create([
            'name' => 'FIBER BROW GEL',
            'price' => 54,
            'description' => 'BALANCE AND SYMMETRY ARE ESSENTIAL TO THE TOM FORD FACE. THIS FIBER-FILLED, WATER-RESISTANT FORMULA BRUSHES ONTO BROWS FOR ALL-DAY WEAR. FILLS IN SPARSE BOWS TO CREATE FULL, NATURAL-LOOKING BROWS THAT ADD SYMMETRY AND BALANCE TO THE FACE. SETS, TAMES AND ENHANCES COLOR IN FIVE INCLUSIVE, LIGHT-TO-DARK SHADES',
            'image' => 'https://i1.adis.ws/i/tom_ford/T3W2_BLONDE_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE FIBER BROW GEL IS A BROWN CYLINDER SHAPE STICK, WITH A TWIST OFF CAP REVELING ITS BROW TIP',
            'categories' => ['women', 'eyes', 'brows'],
        ]);

        Product::create([
            'name' => 'BROW PERFECTING PENCIL',
            'price' => 44,
            'description' => '
            A RETRACTABLE PRECISION PENCIL WITH A 1.5MM POINT EFFORTLESSLY DETAILS BROWS WITH EXPERT EXACTNESS. THE ULTRA-FINE TIP CREATES LONG-LASTING, NATURAL-LOOKING, HAIR-LIKE STROKES SIMILAR TO THE EFFECT OF MICROBLADING. RICH COLOR WITH A MATTE FINISH EASILY BLENDS FOR DESIRED EFFECT',
            'image' => 'https://i1.adis.ws/i/tom_ford/T78C_01BLONDE_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE BROW PERFECTING PENCIL IS ALL BROWN DOUBLE SIDED',
            'categories' => ['women', 'eyes', 'brows'],
        ]);

        Product::create([
            'name' => 'BROW SCULPTOR WITH REFILL',
            'price' => 54,
            'description' => 'TO TOM FORD, THE EYEBROWS ARE ONE OF THE MOST IMPORTANT ELEMENTS OF YOUR FACE ARCHITECTURE. A PERFECTLY GROOMED AND SHAPED BROW IS THE MOST POWERFUL NON-INVASIVE WAY TO DEFINE AND ENHANCE YOUR FEATURES. THE UNIQUE CALLIGRAPHY TIP ALLOWS A TAILOR-MADE STROKE, FROM THIN TO WIDE',
            'image' => 'https://i1.adis.ws/i/tom_ford/T78C_01BLONDE_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'REMOVE THE OPPOSITE-END CAP TO UNCOVER THE GROOMING BRUSH; TWIST THE CAP COUNTERCLOCKWISE TO REVEAL THE SHARPENER. INCLUDES
            ONE REFILL. TO REFILL, PULL OUT EMPTY CARTRIDGE AND INSERT REPLACEMENT UNTIL IT CLICKS',
            'categories' => ['women', 'eyes', 'brows'],
        ]);

        //EYES(EYESHADOW)
        Product::create([
            'name' => 'CREAM COLOR FOR EYES',
            'price' => 46,
            'description' => 'THE LUXURIOUS, CREAM EYE SHADOW ILLUMINATES EYES IN THE LUSTROUS GLOW OF EIGHT, ULTRA-PIGMENTED METALLIC SHADES, FROM THE SUN SPARK GLEAM OF SPHINX TO THE GLITTERING SEA-INSPIRED SIREN BLUE. THE VERSATILE, COOL AND CREAMY FORMULA SEAMLESSLY GLIDES ONTO THE LID TO BRIGHTEN EYES.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T43R_PLATINUM_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE CREAM COLOR FOR EYES IS IN A CIRCULAR CONSEALER, TWISING IT TO OPEN',
            'categories' => ['women', 'eyes', 'eyeshadow'],
        ]);

        Product::create([
            'name' => 'CREAM AND POWDER EYE COLOR',
            'price' => 65,
            'description' => 'INSPIRED BY AN OPULENT, GOLDEN SUN AT ITS ZENITH, BLAZING OVER PRIVATE ISLANDS, THIS TWO-TIERED EYE COLOR CREATES A DRAMATIC AND DEEPLY SEDUCTIVE EYE LOOK. SWEEP THE ULTRA-PIGMENTED, BLACK CREAM BASE COLOR OVER THE LID AND DISCOVER ITS MOLTEN GLOW MADE OF GOLDEN-PEARL SHIMMER, SPARKLING LIKE GLIMMERING RAYS WARMING NAKED SKIN. TOP WITH A LAYER OF HIGH-SHINE, HIGH-GLITTER GOLD-COLORED POWDER TO AMPLIFY THE INCANDESCENT EFFECT AND ADD EXTRAORDINARY DIMENSION TO THE EYES.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T9GK_BLSAND_OS_A?$hires$&bg=rgb(255,255,255)&bg=rgb(255,255,255)',
            'item_detail' => 'THE CREAM AND POWEDER EYE COLOR IS A SMALL ROUND CONSEALER WITH A CLEAR BASE AND A FILP TO OPEN CAP',
            'categories' => ['women', 'eyes', 'eyeshadow'],
        ]);

        //EYES(LINEAR)
        Product::create([
            'name' => 'EMOTIONPROOF EYELINER',
            'price' => 45,
            'description' => 'INTENSE AND RICHLY PIGMENTED EMOTIONPROOF LINER IS WHERE LUXURY MEETS HIGH PERFORMANCE. AN EXTREMELY LONG-WEARING RETRACTABLE EYELINER WITH UP TO 24 HOURS OF WEAR, IN SHADES DESIGNED TO COMPLEMENT TOM FORD EYE SHADOW, GLIDES EFFORTLESSLY ONTO LIDS WITHOUT TUGGING FOR GORGEOUS COLOR PAYOFF. WATERPROOF, NON-SMUDGING, TRANSFER-RESISTANT, HUMIDITY-RESISTANT AND DESIGNED TO STAY PUT, THE EMOTIONPROOF FORMULA IS TRULY READY FOR ANY SITUATION. OPHTHALMOLOGIST-TESTED',
            'image' => 'https://i1.adis.ws/i/tom_ford/T6YF_COMINATEUR_OS_A?$pdp_hero_mob$&&bg=rgb(255,255,255)',
            'item_detail' => 'THE EMOTIONPROOF EYELINER IS A BROWN CIRCULAR PEN SHAPE, WIHT A GOLD LOGO AROUND THE TOP AND A PULL OFF CAP, WITH A SMALL TIP',
            'categories' => ['women', 'eyes', 'liner'],
        ]);

        Product::create([
            'name' => 'EYE KOHL INTENSE',
            'price' => 39,
            'description' => 'RICH. ULTRA-SMOOTH. VERSATILE. A RICHLY PIGMENTED EYELINER FOR A SIGNATURE SMOKEY EYE. CREATE TOM FORDS SIGNATURE SEXY, SMOKEY EYE LOOK WITH THIS INTENSE, KOHL-EFFECT PENCIL. IT COMBINES INNOVATIVE TECHNOLOGY WITH RICH COLOR PIGMENTS AND GLIDES ON SKIN FOR AN ULTRA-FLUID APPLICATION. USE OUTSIDE AND INSIDE THE LID FOR AN INSTANT SENSUAL AND SULTRY EFFECT. INCLUDES CUSTOM SHARPENER',
            'image' => 'https://i1.adis.ws/i/tom_ford/T5A0_ESPRESSO_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE EYE KOHL INTENSE IS ALL BROWN WITH A PULL OFF BROWN CAP, WITH A POINT TIP',
            'categories' => ['women', 'eyes', 'liner'],
        ]);

        //FACE(MASCARA)
        Product::create([
            'name' => 'EXTREME MASCARA',
            'price' => 46,
            'description' => 'COMPLETE THE MESMERIZING TOM FORD EYE WITH DARKLY LUSH SHADES OF TOM FORD EXTREME MASCARA. LASH-FILLING POWDERS AMPLIFY THE EYES DRAMATIC IMPACT AND THE CREAMY FORMULA WORKS TO TRANSFORM LASHES FOR OPTIMAL GLAMOUR AND DRAMA.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T0TM_RAVEN_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE EXTREME MASCARA IS A ALL BROWN DESIGN, WITH A TWISTY CAP REVELING THE MASACARA',
            'categories' => ['women', 'eyes', 'masacara'],
        ]);

        Product::create([
            'name' => 'BADASS MASCARA',
            'price' => 46,
            'description' => 'LUSH. VOLUMINOUS. LONGWEARING.
            BADASS MASCARA PUMPS LASHES UP TO THE EXTREME WITH BIKER JACKET-BLACK INTENSITY. THE ULTIMATE MASCARA FOR EXTRAORDINARY LASHES, BADASS MASCARA IS THE GO-TO POWERHOUSE FOR NON-SMUDGING, LONG-LASTING AND LENGTH.',
            'image' => 'https://i1.adis.ws/i/tom_ford/T77N01_01BADASSBLACK_OS_A?$pdp_hero_dsk$&bg=rgb(255,255,255)',
            'item_detail' => 'THE EXTREME MASCARA IS A ALL WHITE DESIGN, WITH A TWISTY CAP REVELING THE MASACARA',
            'categories' => ['women', 'eyes', 'masacara'],
        ]);
    }
}
